SELECT A.CAR_ID, A.CAR_TYPE, CAST((30 * A.DAILY_FEE) * (1 - C.DISCOUNT_RATE * 0.01) AS SIGNED INTEGER) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B ON A.CAR_ID = B.CAR_ID
    JOIN (SELECT *
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE DURATION_TYPE = '30일 이상') AS C ON A.CAR_TYPE = C.CAR_TYPE
WHERE A.CAR_ID NOT IN (SELECT CAR_ID
                      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                      WHERE DATE_FORMAT(START_DATE, '%Y-%m-%d') <= '2022-11-30'
                      AND DATE_FORMAT(END_DATE, '%Y-%m-%d') >= '2022-11-01'
                      )
AND A.CAR_TYPE IN ('세단', 'SUV')
AND 500000 <= (30 * A.DAILY_FEE) * (1 - C.DISCOUNT_RATE * 0.01) 
AND (30 * A.DAILY_FEE) * (1 - C.DISCOUNT_RATE * 0.01)  < 2000000
GROUP BY CAR_ID
ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID DESC;

/*
- 날짜 between부분 → 대여중인 것의 CAR_ID를 구해서 not in을 사용하기
- `CAST`(~~ AS SIGNED INTEGER) → 정수로 형변환
*/