SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE)+1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVG(DATEDIFF(END_DATE, START_DATE)+1) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;

/*
- 문제 조건을 보면 5/11 - 5/11이 1일이다.
- 근데 DATEDIFF 연산결과는 0이니까, 이 결과에 1을 더해줘야 한다.
*/