(SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3
UNION
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL AS 'USER_ID', SALES_AMOUNT /* 두 번째 테이블에서 없는 정보인 USER_ID를 null로 나타내는 방법이다. */
FROM OFFLINE_SALE
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3)
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;

/*
- 두 테이블을 합쳐야 하는데, group by도 아니고 join도 아니어서 어떻게 해야하는지 고민했다.
- 그냥 union을 해서 각각의 결과를 합쳐주면 된다.

*/