WITH GROUP_BY_EMP AS (SELECT DEPT_ID, ROUND(AVG(SAL), 0) AS AVG_SAL
                     FROM HR_EMPLOYEES
                     GROUP BY DEPT_ID)

SELECT A.DEPT_ID, A.DEPT_NAME_EN, B.AVG_SAL
FROM HR_DEPARTMENT AS A JOIN GROUP_BY_EMP AS B ON A.DEPT_ID = B.DEPT_ID
ORDER BY B.AVG_SAL DESC;